#cloud-config
package_update: true
packages:
  - httpd
write_files:
  - path: /var/www/html/index.html
    content: |
      <html>
      <head>
        <title>Minha Página Web</title>
      </head>
      <body>
        <h1>Bem-vindo ao meu servidor Apache!</h1>
      </body>
      </html>
runcmd:
  - systemctl start httpd
